### ISSUE TITLE
Oh...

### ISSUE THREAD

**Issue by ben2talk** [Etesam913/rounded-fox#1]
Didn't work at all - even tried correcting spelling of 'userchrome.css' to 'userChrome.css'

**Comment by Etesam913** [comment]
Does it look identical to the default firefox? 
Are you using windows?
Did you set toolkit.legacyUserProfileCustomizations.stylesheets to true in about:config?

**Comment by tokyovigilante** [comment]
Works fine for me on windows, possibly check userChrome.css is downloaded or pasted in from raw view, rather than saving the Github page! Rookie mistake I know...
