### ISSUE TITLE
Prevents uBlock origin from displaying element blocker

### ISSUE THREAD

**Issue by tokyovigilante** [Etesam913/rounded-fox#5]
Hey, great extension! Would love some kind of tab indicator, but setting close window with last tab to false is a good workaround.

One issue is that hiding the address bar prevents the uBlock element blocker from displaying, any way to fix this? Haven't tested any other extensions yet.

**Comment by Etesam913** [comment]
Did you try it with the most recent css on the main branch? I think #4 fixes this.

**Comment by tokyovigilante** [comment]
Yes this is from most recent `main`. I do see the window flash for a split second on Linux, not at all on Windows.

**Comment by tokyovigilante** [comment]
Apologies extension windows display fine once the extensions are pinned to the toolbar, thanks!
